### ISSUE TITLE
[FEATURE] Put jupyter-notebooks examples in different repo?

### ISSUE THREAD

**Issue by navidcy** [xgcm/xgcm#264] opened 2020-10-08 20:04 UTC
The repository size is 48M. This seems a bit too much... I guess this is because it includes jupyter notebooks (with rendered figures) clogging the repo's history. 

(This effect can runaway quickly... When I included notebooks with animations in the docs of https://github.com/FourierFlows/GeophysicalFlows.jl pretty quickly the repo's size reached 500MB!]

Perhaps consider splitting the actual code from example notebooks? If you proceed with this, after removing the large-size files you should clean the repo's history with, e..g., https://github.com/rtyley/bfg-repo-cleaner

**Comment by rabernat** [comment] 2020-10-08 22:17
Thanks for the suggestion. This is a duplicate of #258. 😄

**Closed by rabernat** 2020-10-08 22:17 UTC
Labels: enhancement

**Comment by navidcy** [comment] 2020-10-08 23:13
Oops!
