### ISSUE TITLE
"import xgcm" yields "AttributeError: 'NoneType' object has no attribute 'expandtabs'"

### ISSUE THREAD

**Issue by angilkaka** [xgcm/xgcm#210] opened 2020-08-29 22:15 UTC
Hello, 
when I do "import xgcm" in Python, I get the "AttributeError: 'NoneType' object has no attribute 'expandtabs'".
I tested several xgcm installations (conda, pip, pip+git) in newly created conda environments on Mac and Linux platforms. The error stays the same. 
One example:
python
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xgcm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/lib/python3.7/site-packages/xgcm/__init__.py", line 6, in <module>
    from .grid import Grid, Axis
  File "/work//lib/python3.7/site-packages/xgcm/grid.py", line 759, in <module>
    class Grid:
  File "/work/lib/python3.7/site-packages/xgcm/grid.py", line 1067, in Grid
    @docstrings.dedent
  File "/work/lib/python3.7/site-packages/docrep/decorators.py", line 26, in update_docstring
    doc = func(self, args[0].__doc__, *args[1:], **kwargs)
  File "/work/lib/python3.7/site-packages/docrep/__init__.py", line 517, in dedent
    s = inspect.cleandoc(s)
  File "/work/lib/python3.7/inspect.py", line 619, in cleandoc
    lines = doc.expandtabs().split('\n')
AttributeError: 'NoneType' object has no attribute 'expandtabs'

I also tested with an installation of pip install flake8 flake8-expandtab; still the same error. 

Could anyone help me importing xgcm working?

Thanks a lot! A.

**Comment by jbusecke** [comment] 2020-08-31 17:52
Hi @angilkaka, 

thanks for using xgcm and posting this issue. I have never encountered this. Could you post a complete list of installed conda packages in your environment for starters?

Could you try to set up a fresh conda environment with minimal dependencies, so we can narrow down if the problem is with xgcm itself?

@rabernat @dcherian do you have a clue what could be going on here?

**Comment by rabernat** [comment] 2020-08-31 17:55
> Could you post a complete list of installed conda packages in your environment for starters?

Perhaps we could explain how to do this? 😉 Not everyone will know.

> Could you try to set up a fresh conda environment with minimal dependencies, so we can narrow down if the problem is with xgcm itself?

Also this?

**Comment by malmans2** [comment] 2020-08-31 17:59
Just got the same error. I think it has to do with docrep 0.3.0 released a few days ago:

> Several methods have been deprecated in version 0.3. See [Migrating from 0.2.8 to 0.3.0](https://docrep.readthedocs.io/en/latest/#migrating-from-0-2-8-to-0-3-0) for details!

**Comment by jbusecke** [comment] 2020-08-31 18:18
> Perhaps we could explain how to do this? 😉 Not everyone will know.

Sorry, that was a bit hasty indeed. @angilkaka you can do `conda list` in your terminal with your active environment and past the output here. Or just `conda list docrep` (to get just the installed versionnumber of docrep, following @malmans2 suggestion). 

If docrep is indeed at version 0.3.0, I  suggest you set up a new conda environment

I really want to understand docrep better and integrate it more consistently in xgcm, but currently I have some higher priority task on my list. Perhaps in the meantime we can pin the version of docrep to <3.0?

**Comment by jbusecke** [comment] 2020-08-31 18:30
I was able to reproduce the error in a fresh environment with 

```
conda create -n xgcm_issue_test xgcm ipython
```
Then I tried to downgrade docrep with
```
conda install -n xgcm_issue_test docrep=0.2.7
```
which indeed did fix the issue. 

This should definitely be fixed asap.

For a quick fix I suggest pinning to v0.2.7 (0.2.8 was not released on conda-forge it seems). 

I want to understand docrep in more detail and use it consistently in xgcm, but I have other more pressing issues in the pipeline right now and would like to deal with this once I have a bit more bandwidth.

**Comment by angilkaka** [comment] 2020-08-31 19:50
Hello,  indeed, downgrading docrep to 0.2.7 solved my "import xgcm" AttributeError. 
Thanks so much. I really appreciate your support. A.

**Comment by jbusecke** [comment] 2020-08-31 20:35
Ill reopen this until we have a fix on our side. Glad this helped.

**Comment by rabernat** [comment] 2020-09-02 15:04
Was this fixed by #213?

**Comment by jbusecke** [comment] 2020-09-02 15:12
Yes it should be. We should test this after a new release.

**Comment by jbusecke** [comment] 2020-09-03 15:05
Closed via #214

**Closed by jbusecke** 2020-09-03 15:05 UTC
Labels: bug

**Comment by Thomas-Moore-Creative** [comment] 2021-06-24 01:43
Just an FYI on a personal experience / practice. 

I rebuilt a personal `xgcm` environment and received this error on `import`:
`'NoneType' object has no attribute 'expandtabs'`

My approach was taking a particular `pangeo` environment (via: https://github.com/csiro-dcfp/pangeo_hpc/blob/master/pangeo_environment.yml ) and then adding `conda install -c conda-forge xgcm`.
The obvious problem seems that I ended up with `docrep 0.3.2  pyh44b312d_0   conda-forge`

Downgrading `docrep` later via `conda install -c conda-forge docrep=0.2.7` fixed the problem.

**Comment by jbusecke** [comment] 2021-06-24 16:02
That is weird @Thomas-Moore-Creative. Eventually this will be fixed with #319 I believe.

**Comment by avik2007** [comment] 2022-01-20 19:36
I just started receiving this issue out of nowhere today. I'll try downgrading my xgcm but unless upgrading xrft somehow 
affected xgcm, this seems to be unwarranted. 

More details: I upgraded xrft on to get access to some recent changes to that library and then found that "import xgcm" produced the above error. I'm on docrep 0.2.7, any advice on how to fix this issue?

**Comment by jbusecke** [comment] 2022-01-20 21:04
Hi @avik2007, can you post your xgcm version?

**Comment by Thomas-Moore-Creative** [comment] 2022-03-17 23:46
.... a blast from the past but thanks @jbusecke et al for fixing this `docrep` issue in v0.6.0 (2021/11/03).  This issue got me again on a new platform ( with an older version of xgcm ) and had me stumped (again) for a minute but a simple update did the trick.

**Comment by jbusecke** [comment] 2022-03-18 01:45
Awesome to hear!
