### ISSUE TITLE
questions on pangeo-ocean-examples/NCAR CESM High Resolution Ocean Simulation

### ISSUE THREAD

**Issue by DapengLi17** [xgcm/xgcm#183] opened 2020-03-04 23:05 UTC
Hi All:
      I am analyzing the CESM POP high resolution simulation using xgcm. I followed the example page (https://github.com/pangeo-data/pangeo-ocean-examples/blob/master/cesm-pop-highres-ocean.ipynb) and met the following error. When I run 

zeta = ( grid.diff(grid.interp(ds_raw.V1_1 * ds_coords.DYU, 'Y', boundary='extend'), 'X')
       - grid.diff(grid.interp(ds_raw.U1_1 * ds_coords.DXU, 'X'), 'Y', boundary='fill') ) / ds_coords.TAREA
zeta

ds_coords does not have DYU and DXU. So I used ds_raw.DXU and ds_raw.DYU instead and the output looks fine. I wonder are these typos or I missed anything.
    Any comments are highly appreciated. 

Here are the ds_coords and ds_raw

here we strip the coordinates out of the dataset
this makes the calculation below work better
ds_coords = ds_new.coords.to_dataset().reset_coords().drop('time')
ds_raw = ds_new.reset_coords(drop=True)

**Comment by rabernat** [comment] 2020-03-05 02:30
Hi @DapengLi17. Thanks for asking your question in a public forum where others can learn from the discussion.

Unfortunately, I cannot reproduce your problem. I just tried that notebook on binder, and everything worked fine. You can verify this for yourself by following this link:

[![Binder](https://binder.pangeo.io/badge_logo.svg)](https://binder.pangeo.io/v2/gh/pangeo-data/pangeo-ocean-examples/master)

> ds_coords does not have DYU and DXU.

This is not what it looks like to me. 
```python
assert 'DYU' in ds_coords.data_vars
assert 'DXU' in ds_coords.data_vars
```

The full contents of `ds_coords` are shown below:

<details>

```
>>> print(ds_coords)
<xarray.Dataset>
Dimensions:             (nlat_t: 2400, nlat_u: 2400, nlon_t: 3600, nlon_u: 3600, z_t: 62, z_t_150m: 15, z_w: 62, z_w_bot: 62, z_w_top: 62)
Coordinates:
  * z_t                 (z_t) float32 500.0 1500.0 ... 562499.06 587499.06
  * nlat_u              (nlat_u) int64 1 2 3 4 5 6 ... 2396 2397 2398 2399 2400
  * nlat_t              (nlat_t) float64 0.5 1.5 2.5 ... 2.398e+03 2.4e+03
  * nlon_u              (nlon_u) int64 1 2 3 4 5 6 ... 3596 3597 3598 3599 3600
  * z_w_top             (z_w_top) float32 0.0 1000.0 ... 549999.06 574999.06
  * z_w                 (z_w) float32 0.0 1000.0 2000.0 ... 549999.06 574999.06
  * z_w_bot             (z_w_bot) float32 1000.0 2000.0 ... 574999.06 599999.06
  * z_t_150m            (z_t_150m) float32 500.0 1500.0 ... 13500.0 14500.0
  * nlon_t              (nlon_t) float64 0.5 1.5 2.5 ... 3.598e+03 3.6e+03
Data variables:
    vonkar              float64 ...
    rho_air             float64 ...
    KMU                 (nlat_u, nlon_u) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    fwflux_factor       float64 ...
    TLAT                (nlat_t, nlon_t) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    cp_air              float64 ...
    TAREA               (nlat_t, nlon_t) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    T0_Kelvin           float64 ...
    ANGLE               (nlat_u, nlon_u) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    omega               float64 ...
    HUW                 (nlat_u, nlon_t) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    mass_to_Sv          float64 ...
    rho_sw              float64 ...
    dz                  (z_t) float32 dask.array<chunksize=(62,), meta=np.ndarray>
    dzw                 (z_w) float32 dask.array<chunksize=(62,), meta=np.ndarray>
    stefan_boltzmann    float64 ...
    KMT                 (nlat_t, nlon_t) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    HUS                 (nlat_t, nlon_u) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    cp_sw               float64 ...
    days_in_norm_year   timedelta64[ns] ...
    rho_fw              float64 ...
    DXT                 (nlat_t, nlon_t) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    UAREA               (nlat_u, nlon_u) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    HT                  (nlat_t, nlon_t) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    radius              float64 ...
    HU                  (nlat_u, nlon_u) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    latent_heat_fusion  float64 ...
    TLONG               (nlat_t, nlon_t) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    DYT                 (nlat_t, nlon_t) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    salt_to_ppt         float64 ...
    sea_ice_salinity    float64 ...
    heat_to_PW          float64 ...
    salt_to_mmday       float64 ...
    hflux_factor        float64 ...
    ULONG               (nlat_u, nlon_u) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    salinity_factor     float64 ...
    ppt_to_salt         float64 ...
    DXU                 (nlat_u, nlon_u) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    ANGLET              (nlat_t, nlon_t) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    nsurface_u          float64 ...
    ULAT                (nlat_u, nlon_u) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    DYU                 (nlat_u, nlon_u) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    HTN                 (nlat_u, nlon_t) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    sound               float64 ...
    HTE                 (nlat_t, nlon_u) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    sflux_factor        float64 ...
    nsurface_t          float64 ...
    REGION_MASK         (nlat_t, nlon_t) float64 dask.array<chunksize=(2400, 3600), meta=np.ndarray>
    grav                float64 ...
    momentum_factor     float64 ...
    salt_to_Svppt       float64 ...
    ocn_ref_salinity    float64 ...
    latent_heat_vapor   float64 ...
Attributes:
    Conventions:   CF-1.0; http://www.cgd.ucar.edu/cms/eaton/netcdf/CF-curren...
    calendar:      All years have exactly  365 days.
    cell_methods:  cell_methods = time: mean ==> the variable values are aver...
    contents:      Diagnostic and Prognostic Variables
    history:       none
    nsteps_total:  13088337
    revision:      $Id: tavg.F90 41939 2012-11-14 16:37:23Z mlevy@ucar.edu $
    source:        CCSM POP2, the CCSM Ocean Component
    start_time:    This dataset was created on 2013-03-09 at 12:25:55.7
    tavg_sum:      86399.99999999962
    title:         hybrid_v5_rel04_BC5_ne120_t12_pop62
```

</details>

Would you consider providing complete reproducible example of your code which we can cut and paste to verify the problem? Also, please post the full stack trace of your error message.

**Comment by DapengLi17** [comment] 2020-03-05 18:00
Hi @rabernat 
Thanks so much for your reply. Sincerely appreciate your time and work. I tried your notebook on binder and it worked fine. The problem I mentioned early occur when I analyze our CESM POP high resolution simulation. I think the problem is because 'DXU' and 'DYU' are outputted as 'Coordinates' in your notebook on binder while they are outputted as 'Data variables' in our POP simulation. Please see the codes and outputs here [https://github.com/DapengLi17/JupyterNotebook/blob/master/CESM_POP_XGCM_ds_coords_DXUDYU.ipynb](url)

 I think 'ds_coords.DXU' and 'ds_raw.DXU' are the same since 
`ds_coords = ds_new.coords.to_dataset().reset_coords().drop('time')`   
`ds_raw = ds_new.reset_coords(drop=True)` 
So I replaced `ds_coords.DXU` and `ds_coords.DYU` with `ds_raw.DXU` and `ds_raw.DYU` in the gradient calculations. Are these correct?

Thanks again for your kind help. Your time and work are highly appreciated. 
Regards!
Dapeng Li

**Comment by rabernat** [comment] 2020-03-05 18:09
> Are these correct?

Sounds correct to me!

I'm going to close this, since it's not really a bug with xgcm, but rather a question about how the data from your particular model run are formatted.

**Closed by rabernat** 2020-03-05 18:09 UTC

**Comment by DapengLi17** [comment] 2020-03-05 18:13
Hi @rabernat 
    Thanks for your confirmation. Sincerely appreciate your kind help! 
Regards!
Dapeng Li
