### ISSUE TITLE
add 1D regridding

### ISSUE THREAD

**Issue by rabernat** [xgcm/xgcm#68] opened 2017-07-25 18:29 UTC
It would be great to be able to do 1D regridding, say to move from sigma coordinates to depth coordinates.

What is the API we would like to use for such an operation?

cc @roxyboy

**Comment by roxyboy** [comment] 2017-07-25 22:19
I remember creating a regrid package using the KDTree but if not, I think the `scipy.interpolation` api should be fine. We could create a wrapper function so that it'll work on `dask.array`

**Comment by jbusecke** [comment] 2018-07-30 15:03
I have implemented this as an interpolation approach here (https://github.com/jbusecke/xarrayutils/blob/master/xarrayutils/utils.py)

But I think we would want some additional functionality:
1) Performance improvement using [numba](https://numba.pydata.org)
2) A conservative remapping (instead of interpolation?)

I am also wondering if xgcm is the right module. E.g. what unique internal 'knowledge' does the xgcm grid operator have that makes this task easier?

```
def _coord_remapping_interp(x, y, y_target, remap):
    """Remap dataarray onto new dimension. E.g. express y(x) as y(remap)
    using interpolation"""
    idx = np.logical_or(np.isnan(y_target), np.isnan(y))
    if sum(~idx) < 2:
        y_remapped = remap * np.nan
    else:
        y_remapped = interpolate.interp1d(y_target[~idx], y[~idx],
                                          bounds_error=False)(remap)
    return y_remapped


def coord_remapping(x, y, y_target, remap, x_dim=None, remap_dim=None):
    """
    remaps datasets/dataarray `y` with coordinate `x` to new coordinate
    `y_target` with values specified in `remap`
    E.g. a dataset with coordinate depth(x) will be remapped to coordinate
    temp(y_target) as a vertical coordinate, with spacing given by `remap`)
    Parameters
    ----------
    x: xr.DataArray
        The original dim/coordinate used for remapping
    y: {xr.DataArray, xr.Dataset}
        the data to be remapped
    y_target: xr.DataArray
        The new coordinate used for remapping
    remap: {range, np.array, xr.DataArray}
        Values of `y_target` used as new coordinate.
    Returns
    -------
    remapped_y: xr.Dataset
        dataset with remapped variables of y and the remapped position of
        x (e.g. depth of the temperature values given in remap)
    """

    # infer dim from input
    if x_dim is None:
        if len(x.dims) != 1:
            raise RuntimeError('if x_dim is not specified, \
                               x must be a 1D array.')
        dim = x.dims[0]
    else:
        dim = x_dim

    if remap_dim is not None:
        raise RuntimeError('multidim remap is not implemented yet.')

    # if dataset is passed drop all data_vars that dont contain dim
    if isinstance(y, xr.Dataset):
        drop_vars = [a for a in y.data_vars if dim not in y[a].dims]
        if drop_vars:
            print('Found incompatible data variables (%s) in dataset. They do \
            not contain the dimension `%s` and will be dropped.' \
            % (drop_vars, dim))
            y = y.drop(drop_vars)

    # convert remap to dataarray?
    if not isinstance(remap, xr.DataArray):
        remap = xr.DataArray(remap, coords=[('remapped_dim', remap)])

    args = (y_target, remap)
    kwargs = dict(
            input_core_dims=[[dim], [dim], [dim], ['remapped_dim']],
            output_core_dims=[['remapped_dim']],
            vectorize=True,
            dask='parallelized',
            output_dtypes=[y_target.dtype],
            output_sizes={'remapped_dim': len(remap)}
                )

    remapped_y = xr.apply_ufunc(_coord_remapping_interp, x, y, *args, **kwargs)

    remapped_pos = xr.apply_ufunc(_coord_remapping_interp, x, x, *args,
                                  **kwargs)
    remapped_y.coords['remapped_%s' % x.name] = remapped_pos
    return remapped_y
```

**Comment by raphaeldussin** [comment] 2018-07-30 15:32
Hi Julius,

I have got a python-wrapped fortran code for vertical interpolation, maybe that can
speed up things.

https://github.com/raphaeldussin/MITgcm-recipes/blob/master/pre-processing/regridding/mod_akima_1d.f90

**Comment by jbusecke** [comment] 2018-07-30 15:41
Sweet. Can you handle all dependencies through conda with this? I definitely do not want to break the 'ease' of a conda installation.
In the long term I think there need to be several options for interpolation/regridding to mimic specific model codes, so we could add several ways and then benchmark them too.

But in terms of my second question. I am not sure if this is a 'core' xgcm functionality: For things like #103 #98, xgcm is essential in providing the gridsetup context. I think in both our examples, there is no difference whether this would be done with xgcm or just as a stand alone function.

What do you think?

No matter whether this will be part of xgcm, I think these methods need to be collected and somewhat 'standardized', so this is really helpful!

**Comment by rabernat** [comment] 2018-07-30 15:53
I hope you all know that xarray now has 1D and multidimensional interpolation.
http://xarray.pydata.org/en/latest/interpolation.html

The caveat is that it only works with dimension coordinates, so it can't do full geometrically correct conservative regridding. For that, there is xesmf: http://xesmf.readthedocs.io/en/latest/l

Given our difficulty keeping up with basic maintenance of xgcm, I am very cautious about adding big new features like interpolation. My strong preference would be to rely on these other packages for interpolation as much as possible.

**Comment by jbusecke** [comment] 2018-07-30 15:56
Ah cool. I wasnt aware of xesmf. That looks very helpful.

I agree, that we should conserve the energy for features that are unique to this package. 

Closing

**Comment by jaard** [comment] 2019-06-14 09:30
I am currently stuck with this issue, trying to interpolate from 3-D depth array on sigma-levels in ROMS to a new z-level dimension. Unfortunately xarray interpolation doesn't work as @rabernat pointed out, since the depth is not a dimension (yet). I would like to push xarray a bit in the ROMS/CROCO community, but a clean xarray/dask way of doing the interpolation from sigma-levels to z-levels is still needed to be really convincing ;-)

@jbusecke, were you successful solving this regridding problem with xesfm? If so, it would be great if you could share an example since I haven't figured it out yet. More generally, I was thinking that this kind of example should probably be included (or linked to) in the xarray documentation. I totally understand if xarray can't provide advanced interpolation / regridding functions at this point, but still people are running into this issue and it would be a shame if that kicks them out of the great xarray workflow. There are also a few unanswered questions on stackoverflow around this topic, therefore I think the problem is not uncommon.

**Comment by jbusecke** [comment] 2019-06-14 11:16
I have implemented a dask friendly version of ‘groupby_bins’ which conserves tracer content [here](https://github.com/jbusecke/xarrayutils/blob/master/xarrayutils/vertical_remapping.py).
I have successfully tested it going from z to density coordinates. It is not super well documented but Id be happy to work further on it if there is interest. Do you want to give it a try and report back?

**Comment by jaard** [comment] 2019-06-14 12:24
Thanks! I will try your solution and report back.
I got a similar example of using binning from @willirath a few days ago, but I was reluctant to follow that path because I haven't completely wrapped my head around it yet.

Does your solution give similar result as simple linear interpolation between two levels?
Obviously linear interpolation doesn't conserve tracers, but that's how the MATLAB Romstools have been handling this so far (at least vor visualisation purposes) so I wanted to have this simple case implemented first. Unfortunately its not so simple to do in a clean & fast way... maybe your method is more straightforward after all.

**Comment by jaard** [comment] 2019-06-14 12:26
One more question: How does your code handle boxes that cross the boundaries of the new bins? Sure there must be some interpolation involved there?

**Comment by willirath** [comment] 2019-06-14 13:11
See https://gist.github.com/willirath/9479c62e8db1c1e4f233d949d2f0f460 for an xarray native approach to vertical linear interpolation.  Not sure this is the way to go.  But it may be instructive for understanding the performance critical aspects of parallelized regridding.

**Comment by jbusecke** [comment] 2019-06-14 13:14
It does not. That is one (quite strong) limitation. 

I am very interested in this functionality and I think my goal would be to emulate the functionality of the [MOM6 code](https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/ALE/MOM_remapping.F90).
Their term for converting from one arbitrary vertical coordinate system into another is ‘remapping’. I believe it is general enough to handle any kind of vertical coordinate system. 

I think that this would however not be suitable as core functionality for either xarray or xgcm (@rabernat do you agree?), we should probably start a ‘xremapping’ or similar. 

It should be a very focused and small package( while remaining general, e.g. work with all b/c-grid models independent of vertical coordinate).
We can use dask and numba to make it nice and fast since this really only operates on a single profile at a time. 

But before we reinvent the wheel, we should ask around a bit if something like this (partially) exists.

Let me know what you think.

ccing: @adcroft @raphaeldussin
Is there a python implementation of the MOM6 remapping algorithm available?

**Comment by jbusecke** [comment] 2019-06-14 13:21
Thinking more about it maybe it is within the scope of xgcm.

One way or the other I think it would he tremendous to converge various model communities into one general software package to achieve these common operations!

**Comment by rabernat** [comment] 2019-06-14 14:11
Xhistogram will really help with this
https://github.com/xgcm/xhistogram

It’s basically ready for release. Just needs some examples in the docs.

**Comment by raphaeldussin** [comment] 2019-06-14 14:12
My 2 cents (since I've been tagged :) ) : 

* for z to terrain following coordinates interpolation, I had it coded a while back into sosie here:

https://github.com/brodeau/sosie

however sosie is a standalone fortran code and at some point I needed a vertical interpolation in python.
My quick and dirty approach was to wrap the fortran with f2py, and it's quick. I have an example of this here:

https://github.com/raphaeldussin/MITgcm-recipes/blob/33b21abff86d16477ac62dd8553c69605c2e0721/MITgcm_recipes/regridding.py#L228

I'd love to see some robust implementation of vertical regridding in xarray.

**Comment by willirath** [comment] 2019-06-16 14:04
@rabernat Xhistogram looks awesome!  Here's a self-contained (using xarray's builtin demo data) example of an area-weighted histogram of geo-referenced temperature data: https://gist.github.com/willirath/aa78cdf1fa9399b0252bbcddab9382a5

**Comment by jbusecke** [comment] 2020-06-23 01:16
Just want to loop everyone in this issue in. @rabernat started an implementation of this functionality in #205. Comments are very welcome.

**Comment by jbusecke** [comment] 2020-09-02 21:45
I would like to consolidate all discussions about regridding into #205. Closing this.

**Closed by jbusecke** 2020-09-02 21:45 UTC
